name: CI/CD

on:
  push:
    branches:
        - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@2
        - uses: actions/setup-node@v2
          with: 
                12.x, node-version: 12
        - run:  npm ci #this means install
        - run:  npm test
        - run:  npm run build
        - run:  npm run deploy
              
