name: CI/CD

on:
    push:  
      branches:
          - master
jobs:
    build:
      runs-on:  ubuntu-latest
        
      steps:
          - uses: actions/setup-node@v1

            with:
              node-version: '12.x'

          - run: npm install
          - run: npm test
          - run: npm run build
          - run: npm run deploy
